### PR TITLE
implement transpilation of optional binding

### PR DESCRIPTION
**Pull request by koher**

### CODE REVIEW

**Review by rintaro — COMMENTED** [review]
Changes in Parser LGTM.
Could you add some test cases in `ParseStmtTests.swift`?

**Comment by koher** [comment]
OK. I'll do it later.

**Comment by koher** [comment]
I added the tests.

**Comment by koher** [comment]
Also supported optional binding like `if let foo = foo {}`.

**Review by rintaro — APPROVED** [review]
LGTM

**Pull request merged**
