### PR TITLE
Supporting library namespace

### PR DESCRIPTION
**Pull request by masarusanjp**
Introduce the function to embed supporting library using namespace.

### ex) 

- usage
```swift
let script = SupportingLibrary.javaScript(for: Set([.optionalCast, .forceCast]), namespace: "$ss")
print(script)
```

- result
```javascript
$ss = {};
((globalObj) => {
    function asx(expression, type_test) {
      if type_test() {
        throw Error("Failed to cast");
      }
      return expression;
    }
    globalObj.asx = asx;
    function asq(expression, type_test) {
      return type_test() ? expression : null;
    }
    globalObj.asq = asq;
})($ss);
```

### CODE REVIEW

**Comment by koher** [comment]
Seems good. I'll check the details later (might be several days later💦).

**Comment by koher** [comment]
Looks good mostly👍

I noticed that the followings.

- [ ] `nicCoalescing` must be a typo.
- [ ] it seems consistent that `is` has another name like `typeCheck`.
- [ ] I think `force***` should be `forced***`.
- [ ] `optionalChain` may be `optionalChaining`.

**Comment by masarusanjp** [comment]
@koher Thank you for your review!
I fixed the names.

**Comment by koher** [comment]
LGTM😃

**Pull request merged**
